<?xml version="1.0"?>
<robot
  xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="wheel_radius" value="0.075"/>
  <xacro:property name="wheel_separation" value="0.355"/>

  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <alwaysOn>false</alwaysOn>
      <legacyMode>false</legacyMode>
      <updateRate>20</updateRate>
      <leftJoint>left_wheel_joint</leftJoint>
      <rightJoint>right_wheel_joint</rightJoint>
      <wheelSeparation>${wheel_separation}</wheelSeparation>
      <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
      <torque>20</torque>
      <commandTopic>/twist_mux/cmd_vel</commandTopic>
      <odometryTopic>/val2/base_controller/odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>base_footprint</robotBaseFrame>
      <rosDebugLevel></rosDebugLevel>
      <publishWheelTF>false</publishWheelTF>
      <publishOdomTF>true</publishOdomTF>
      <publishWheelJointState>false</publishWheelJointState>
      <wheelAcceleration>0</wheelAcceleration>
      <wheelTorque>5</wheelTorque>
      <!-- <odometrySource></odometrySource> -->
      <publishTf>1</publishTf>
    </plugin>
  </gazebo>

</robot>